#!/usr/bin/env python
import sys
from subprocess import call

files = map(open, sys.argv[1:4])

command = ['flocker-changestate'] + [f.read() for f in files] + sys.argv[4:]

print command

call(command)
